# Generated by Django 3.0.7 on 2020-06-25 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('brief_description', models.TextField(blank=True, default='')),
                ('minimum_price', models.IntegerField(default='0')),
                ('quantity_available', models.IntegerField(default='0')),
                ('negotiable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='FarmerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_names', models.CharField(max_length=255)),
                ('telephone_number', models.IntegerField(default='0775058319', max_length=13, unique=True)),
                ('location', models.CharField(max_length=50)),
                ('farm_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.ProductInfo')),
            ],
        ),
    ]
