# Generated by Django 3.0.7 on 2020-06-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20200625_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/farmer_pics'),
        ),
    ]
