# Generated by Django 3.0.7 on 2020-07-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_farmerinfo_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/farmer_pics/%Y/%m/%d'),
        ),
    ]
