# Generated by Django 3.0.7 on 2020-06-25 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TraderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_names', models.CharField(max_length=255)),
                ('telephone_number', models.IntegerField(default='0756479646', max_length=13, unique=True)),
                ('market_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.MarketInfo')),
                ('vending_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.ProductInfo')),
            ],
        ),
    ]
