# Generated by Django 3.0.7 on 2020-06-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderinfo',
            name='telephone_number',
            field=models.IntegerField(default='0756479646', unique=True),
        ),
    ]
